_target_: robot_io.calibration.gripper_cam_calibration.GripperCamPoseSampler
_recursive_: false
initial_pos: [0.3, 0.1, 0.15]
initial_orn: ???
theta_limits: [2.36, 3.93]
r_limits: [0.03, 0.05]
h_limits: [-0.02, 0.02]
trans_limits: [-0.01, 0.01]
yaw_limits: [-0.087, 0.087]
pitch_limit: [-0.087, 0.087]
roll_limit: [-0.087, 0.087]