_target_: robot_io.robot_interface.panda_ros_interface.PandaRosInterface
_recursive_: false
force_threshold: 10
torque_threshold: 10
k_gains: 0.25
d_gains: 0.5
ik_solver: 'kdl'
rest_pose: [-1.465, 1.481, 1.525, -2.435, -1.809, 1.855, -1.231]  # [[x_min, y_min, z_min], [x_max, y_max, z_max]]
workspace_limits:  [[0.3, -0.5, 0.1], [0.6, 0.5, 0.5]]  # [x, y, z, rot_x, rot_y, rot_z]
use_impedance: true