_target_: robot_io.robot_interface.panda_ros_interface.PandaRosInterface
_recursive_: false
force_threshold: 10
torque_threshold: 10
k_gains: 0.25
d_gains: 0.5
ik_solver: 'kdl'
rest_pose: [-1.465, 1.481, 1.525, -2.435, -1.809, 1.855, -1.231]