_target_: robot_io.robot_interface.panda_ros_interface.PandaRosInterface
_recursive_: false

defaults:
  - workspace: half_cylinder
  - _self_

force_threshold: 10
torque_threshold: 10
k_gains: 0.25
d_gains: 0.5
ik_solver: 'kdl'
use_impedance: true