_target_: robot_io.input_devices.space_mouse.SpaceMouse
_recursive_: false
act_type: 'continuous'
sensitivity: 100
mode: '5dof'
initial_gripper_state: 'open'
dv: 0.005
drot: 0.03
action_params:  # set according to robot
  impedance: false
  path: "lin"
  ref: "rel"