_target_: robot_io.input_devices.keyboard_input.KeyboardInput
_recursive_: false
initial_gripper_state: 'open'
dv: 0.005
drot: 0.02
mode: '5dof'
action_params:  # set according to robot
  impedance: false
  path: "lin"
  ref: "rel"