_target_: robot_io.cams.kinect4.kinect4_threading.Kinect4
_recursive_: false
device: 0
align_depth_to_color: true
config_path: config/default_config_kinect4.json
params_file_path: config/kinect4_params_720p.npz
undistort_image: true
resize_resolution: [200, 150]
crop_coords: [301, 623, 516, 946]
fps: 30